---
new_page_extension: md
auto_deploy: false
admin_path: nulis
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page-template
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post-template
upload_dir: blog-media
public_path: https://aditaja-bucket.s3-ap-southeast-1.amazonaws.com/blog-media
front_matter_path: ''
use_front_matter_path: false
file_template: ":year::month::day:-:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
